import { useCallback, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Shell from '../components/ui/Shell'
import LoadingSkeleton from '../components/ui/LoadingSkeleton'
import { createUser, listUsers } from '../api/client'
import { useAuth } from '../context/AuthContext'

export default function AdminPanel() {
  const navigate = useNavigate()
  const { username: signedInAs } = useAuth()
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [isAdmin, setIsAdmin]   = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState(null) // { ok: bool, message: string }

  const [users, setUsers]       = useState(null) // null = loading, [] = none, [...] = loaded
  const [usersError, setUsersError] = useState(null)

  const refreshUsers = useCallback(() => {
    setUsersError(null)
    listUsers()
      .then(setUsers)
      .catch(err => {
        const detail = err?.response?.data?.detail
        setUsersError(typeof detail === 'string' ? detail : 'Could not load users.')
        setUsers([])
      })
  }, [])

  useEffect(() => { refreshUsers() }, [refreshUsers])

  const isValid = username.trim().length >= 3 && password.length >= 6

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!isValid || submitting) return
    setSubmitting(true)
    setResult(null)
    try {
      const data = await createUser(username.trim(), password, isAdmin)
      setResult({
        ok: true,
        message: `User "${data.username}" created${data.is_admin ? ' as admin' : ''}.`,
      })
      setUsername('')
      setPassword('')
      setIsAdmin(false)
      refreshUsers()
    } catch (err) {
      const detail = err?.response?.data?.detail
      setResult({
        ok: false,
        message: typeof detail === 'string' ? detail : 'User creation failed.',
      })
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Shell>
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="mb-6 pb-6 border-b border-border">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-1.5 h-1.5 rounded-full bg-amber" />
            <span className="font-mono text-[10px] tracking-widest text-amber">ADMIN PANEL</span>
          </div>
          <h1 className="text-2xl font-semibold text-text-primary mb-1">User management</h1>
          <p className="text-sm text-text-secondary">
            Signed in as <span className="font-mono text-text-primary">{signedInAs || 'unknown'}</span>.
            Create accounts for reviewers, fieldworkers, or other admins.
          </p>
        </div>

        {/* Clarifying note: Users vs Profiles */}
        <div className="mb-6 p-4 border border-border bg-raised rounded-lg">
          <p className="font-mono text-[10px] tracking-widest text-text-secondary uppercase mb-2">
            Heads up · Users ≠ Profiles
          </p>
          <p className="font-mono text-xs text-text-secondary leading-relaxed">
            Users created here are <span className="text-text-primary">login accounts</span> — they sign in at <span className="text-text-primary">/login</span>.
            They will <span className="text-amber">not</span> appear in <a href="/profiles" className="text-green underline">Profiles</a>,
            which lists worker <span className="text-text-primary">skill records</span> generated by the 5-step onboarding wizard.
            The two are separate concepts in the system.
          </p>
        </div>

        {/* Create user form */}
        <form onSubmit={handleSubmit} className="bg-surface border border-border rounded-lg p-6 mb-6">
          <p className="font-mono text-[10px] tracking-widest text-text-secondary uppercase mb-4">
            Create user
          </p>

          <div className="flex flex-col gap-4">
            <div>
              <label htmlFor="admin-username" className="form-label">Username</label>
              <input
                id="admin-username"
                type="text"
                value={username}
                onChange={e => setUsername(e.target.value)}
                placeholder="e.g. reviewer_jane"
                autoComplete="off"
                className="dark-input"
              />
            </div>
            <div>
              <label htmlFor="admin-password" className="form-label">Password (≥ 6 chars)</label>
              <input
                id="admin-password"
                type="password"
                value={password}
                onChange={e => setPassword(e.target.value)}
                autoComplete="new-password"
                className="dark-input"
              />
            </div>
            <label className="flex items-center gap-3 cursor-pointer select-none">
              <input
                type="checkbox"
                checked={isAdmin}
                onChange={e => setIsAdmin(e.target.checked)}
                className="w-4 h-4 accent-[#1aA882]"
              />
              <span className="font-mono text-xs text-text-secondary">
                Grant admin privileges (delete & review profiles, manage users)
              </span>
            </label>
          </div>

          <div className="flex items-center gap-3 mt-6">
            <button
              type="button"
              onClick={() => navigate('/profiles')}
              className="btn-ghost flex-1"
            >
              ← Profiles
            </button>
            <button
              type="submit"
              disabled={!isValid || submitting}
              className="btn-primary flex-1"
            >
              {submitting ? 'Creating…' : 'Create user'}
            </button>
          </div>

          {result && (
            <p className={`mt-4 font-mono text-xs ${result.ok ? 'text-green' : 'text-red'}`}>
              {result.ok ? '✓ ' : '⚠ '}{result.message}
            </p>
          )}
        </form>

        {/* Existing users */}
        <div className="bg-surface border border-border rounded-lg p-6">
          <div className="flex items-center justify-between mb-4">
            <p className="font-mono text-[10px] tracking-widest text-text-secondary uppercase">
              Existing users {users ? `· ${users.length}` : ''}
            </p>
            <button
              onClick={refreshUsers}
              className="px-3 py-1 border border-border bg-raised font-mono text-[10px] text-text-secondary tracking-widest rounded hover:border-green/40 hover:text-green transition-colors"
            >
              REFRESH
            </button>
          </div>

          {usersError && (
            <p className="font-mono text-xs text-red mb-3">⚠ {usersError}</p>
          )}

          {users === null && <LoadingSkeleton lines={3} />}

          {users && users.length === 0 && !usersError && (
            <p className="font-mono text-xs text-text-muted italic">No users found.</p>
          )}

          {users && users.length > 0 && (
            <div className="overflow-hidden rounded border border-border">
              <table className="w-full text-sm">
                <thead className="bg-raised">
                  <tr className="text-left">
                    <th className="px-3 py-2 font-mono text-[10px] tracking-widest text-text-secondary">ID</th>
                    <th className="px-3 py-2 font-mono text-[10px] tracking-widest text-text-secondary">Username</th>
                    <th className="px-3 py-2 font-mono text-[10px] tracking-widest text-text-secondary">Role</th>
                  </tr>
                </thead>
                <tbody className="bg-surface divide-y divide-border">
                  {users.map(u => (
                    <tr key={u.id ?? u.username}>
                      <td className="px-3 py-2 font-mono text-xs text-text-secondary">#{u.id ?? '—'}</td>
                      <td className="px-3 py-2 text-text-primary">
                        {u.username}
                        {u.username === signedInAs && (
                          <span className="ml-2 font-mono text-[9px] text-text-muted">(you)</span>
                        )}
                      </td>
                      <td className="px-3 py-2">
                        {u.is_admin ? (
                          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full border border-amber-dim bg-amber-faint font-mono text-[9px] text-amber tracking-widest">
                            ADMIN
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full border border-border bg-raised font-mono text-[9px] text-text-secondary tracking-widest">
                            USER
                          </span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </Shell>
  )
}
